#' Save dot file
#'
#' @param graphv Graph generated by diagrammR
#' @param filename Character vector specifying file name
#'
#' @return Writes a file in dot notation suitable for eg. Atom.
#' @export
#'
#' @examples NA
save_dot <- function(graphv, filename){
  dot_output <- DiagrammeR::generate_dot(graphv)
  dot_output <- gsub("\'","\"",dot_output) #because diagrammR does this wrong
  cat(dot_output,file = paste(filename))
}
